---
- name: "Include sudo group determination"
  include_tasks: determine_sudo_group.yml
- name: ssh_users | Set users to deploy
  set_fact:
    ssh_users_deploy_users: >-
      {{ hostvars[inventory_hostname][ssh_users_effective_target_group]
      if ssh_users_effective_users | default([]) in ['', [], '[]', None]
      else hostvars[inventory_hostname][ssh_users_effective_target_group] |
      dict2items | selectattr('key', 'in', ssh_users_effective_users) |
      items2dict }}
- name: ssh_users | Assert that filtered users exist
  assert:
    that:
      - "ssh_users_deploy_users not in ['', {}, '{}', None]"
    msg: "No users selected for deployment."
    quiet: "true"
- name: ssh_users | Remove authorized_keys
  file:
    path: "/etc/ssh/authorized_keys"
    state: "absent"
- name: ssh_users | Create users
  user:
    name: "{{ item.key }}"
    uid: "{{ item.value.uid }}"
    group: "root"
    groups: "{{ sudo_group }}"
    shell: "/bin/bash"
    createhome: "yes"
    generate_ssh_key: "no"
    remove: "yes"
    force: "yes"
    state: "{{ item.value.state }}"
  loop: "{{ ssh_users_deploy_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- name: ssh_users | Create ssh keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value.rsa }}"
    state: "{{ item.value.state }}"
    exclusive: "yes"
  loop: "{{ ssh_users_deploy_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
